### ISSUE TITLE
Cannot require capistrano/puma/nginx

### ISSUE THREAD

**Issue by Jonic** [seuros/capistrano-puma#100]
I'm having trouble with requiring the nginx plugin in my Capfile. Here's the contents of my Capfile:

```
# Load DSL and Setup Up Stages
require 'capistrano/setup'
require 'capistrano/deploy'

require 'capistrano/rails'
require 'capistrano/rails/assets'
require 'capistrano/bundler'
require 'capistrano/rvm'
require 'capistrano/puma'
require 'capistrano/puma/nginx'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

Am I being an idiot? The file is definitely there in the gem! Any idea what I might be doing wrong?

**Comment by seuros** [comment]
You are probably using the wrong gem.

do you have `gem 'capistrano3-puma' , group: :development` in your gemfile ?

**Comment by itsNikolay** [comment]
probably `$ bundle update capistrano3-puma`

**Comment by Jonic** [comment]
Thanks for replying :) Here's that bit of my Gemfile:

```
group :development do
  gem 'quiet_assets'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano3-puma', github: 'seuros/capistrano-puma'
end
```

Running `bundle show capistrano3-puma` shows me that the gem is being installed properly, and if I look inside the gem I can see the nginx file there. The monit, workers, and jungle plugins all include fine with no problems, but it refuses to see the nginx one!

Any ideas?

**Comment by seuros** [comment]
could you remove `github: 'seuros/capistrano-puma'`

**Comment by Jonic** [comment]
That worked. I have no idea why it wasn't working before! The file was definitely there in the gem's code before! Ah well, thanks for your help :)

**Comment by seuros** [comment]
You had a older version installed locally `gem list` and since you didn't use bundler (bundle exec cap...), ruby was requiring that older version.
