### ISSUE TITLE
puma:jungle:install => debian not recognized

### ISSUE THREAD

**Issue by olance** [seuros/capistrano-puma#106]
The jungle install task does not recognize my system, but it _is_ a Debian!

The task tests for the presence of `/etc/lsb-release`, however I have found the following:

> Note that /etc/lsb-release is not specified by the Linux Standard
> Base; only the lsb_release command is (and Debian's version of the
> lsb_release command doesn't require /etc/lsb-release to work, unless
> it's providing information about a derived distribution and not Debian
> proper).  Any code that depends on the existence or content of
> /etc/lsb-release is IMHO broken.

(source: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=444678)

So there should probably be another way to find out whether current system is a debian flavor one?

**Comment by yurijmi** [comment]
Still not fixed :(

I guess for now we'll have to stick with ```touch /etc/lsb-release``` on target machine.
