### ISSUE TITLE
puma doesn't start with puma:jungle:start

### ISSUE THREAD

**Issue by olance** [seuros/capistrano-puma#107]
I'm a bit puzzled at this one...

When I run `cap staging puma:jungle:start` I get this output:
```
DEBUG [342a26f6] Running /usr/bin/env [ -d ~/.rbenv/versions/2.1.5 ] as user@hostname
DEBUG [342a26f6] Command: [ -d ~/.rbenv/versions/2.1.5 ]
DEBUG [342a26f6] Finished in 0.342 seconds with exit status 0 (successful).
INFO [ce509ef0] Running /usr/bin/env sudo service puma start /var/www/appname/staging/current as user@hostname
DEBUG [ce509ef0] Command: ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.5 /usr/bin/env sudo service puma start /var/www/appname/staging/current )
DEBUG [ce509ef0] 	--> Woke up puma /var/www/appname/staging/current:
DEBUG [ce509ef0] 	user user:
DEBUG [ce509ef0] 	log to :
DEBUG [ce509ef0] 	start-stop-daemon --verbose --start --chdir /var/www/appname/staging/current --chuid user --background --exec /usr/local/bin/run-puma /var/www/appname/staging/current :
```

Everything seems to look fine, however puma doesn't actually run after that.
If I log into my server using the same user, copy and run the launch command:
`start-stop-daemon --verbose --start --chdir /var/www/appname/staging/current --chuid user --background --exec /usr/local/bin/run-puma /var/www/appname/staging/current`

Then everything starts correctly. Any idea ? :/

**Comment by juanpedrojose** [comment]
Same here.

However invoking `cap staging puma:start` works fine and `cap staging puma:jungle:status` read status correctly.

**Comment by olance** [comment]
Hmm, I am not using RVM but rbenv, however it might as well be a env-related/path problem

**Comment by wongyouth** [comment]
It only works with no `--background` option in my case.

    start-stop-daemon --verbose --start --chdir /var/www/appname/staging/current --chuid user --exec /usr/local/bin/run-puma /var/www/appname/staging/current


OS: Ubuntu 14.04
puma version: 2.11.3
ruby with rbenv installed

**Comment by Preen** [comment]
@juanpedrojose - The source ~/.profile worked great, thanks!

**Comment by troelskn** [comment]
I had a similar issue, and I'm not using rvm or rbenv. However, when I looked inside `run-puma` I noticed that the `-u` argument was empty. E.g.:

````
exec sudo -u  sh -c "exec puma -C /var/www/appname/shared/puma.rb --daemon"
````

After changing it to:
````
exec sudo -u ubuntu sh -c "exec puma -C /var/www/appname/shared/puma.rb --daemon"
````

it works. (I'm using `ubuntu` as my deployment account, which probably isn't best practise, but just replace it with whatever you want your app server to run as)

**Comment by vedant1811** [comment]
@troelskn I am facing the same issue, user is blank. How can I setup run-puma?
