### ISSUE TITLE
Bundler::GemfileNotFound every keep_releasesth release

### ISSUE THREAD

**Issue by sime** [seuros/capistrano-puma#109]
Hello.

I've being battling this problem since I have started using Puma. my `:keep_releases` is not set and thus it defaults to 5.

Every fifth release I get the following error:
```ruby
/home/production/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/definition.rb:22:in `build': /home/production/site/releases/20150618214643/Gemfile not found (Bundler::GemfileNotFound)
        from /home/production/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler.rb:155:in `definition'
        from /home/production/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler.rb:118:in `setup'
        from /home/production/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/setup.rb:18:in `<top (required)>'
        from /home/production/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/production/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```
That Gemfile does not exist and it was the most recently removed release. It looks like `prune_bundler` does not support symlinks.

puma.rb
```ruby
#!/usr/bin/env puma

directory '/home/production/site/current'
rackup "/home/production/site/current/config.ru"
environment 'production'

pidfile "/home/production/site/shared/tmp/pids/puma.pid"
state_path "/home/production/site/shared/tmp/pids/puma.state"
stdout_redirect '/home/production/site/shared/log/puma_access.log', '/home/production/site/shared/log/puma_error.log', true

threads 0,16

bind 'unix:///home/production/site/shared/tmp/sockets/puma.sock'
workers 0

prune_bundler
```

Should I switch to phased?

**Comment by sime** [comment]
Looks like the `on_restart` block in the `preload_app` works for `prune_bundler` as well.

So I set my staging site to `keep_releases` to 1 and every deploy puma would complain about a missing Gemfile. So I set `puma_preload_app` to true and deployed a new config: `cap staging puma:config`.

I deployed to staging 3-4 times and puma stayed up.

I noticed the new puma.rb contains a new on_restart block: https://github.com/seuros/capistrano-puma/commit/34342d260745487ca97dc94bf8aaea0aaadb3fa5#diff-90aaf0757368b86675fcf483fe962ef4R25

This seemed to be an obvious missing link for the pruning configuration. I stopped puma, swapped in prune_bundler and deployed several times and puma stayed up.

I feel like the on_restart block should be available by default.

**Comment by seuros** [comment]
Thanks

**Comment by sime** [comment]
Sweet! Wasn't 100% sure if I was missing something.

**Comment by seuros** [comment]
pushed new version

**Comment by theonegri** [comment]
@seuros  Pretty dump question but I have the same issue, how can make my cap file use the same version?

**Comment by seuros** [comment]
use latest version : ```cap production puma:config``` to update your puma.rb
and try again.

**Comment by theonegri** [comment]
@seuros I did run `cap production puma:config` but I'm still getting `Gemfile not found (Bundler::GemfileNotFound` Not sure if my puma.rb got updated.

**Comment by sime** [comment]
@seuros Check you don't have an old puma.rb.erb in config/deploy/templates
