### ISSUE TITLE
should puma:check happen after deploy:updating

### ISSUE THREAD

**Issue by alauper** [seuros/capistrano-puma#112]
I have my puma config checked into [proj_root]/config/puma/qa.rb.  I was using unicorn and switched to puma.  For the first time deploy with puma, the puma:check fails because it can't find my config file.  I've defined the puma_conf variable but it depends on release_path or current_path.  But those aren't defined until deploy:updating.

I don't want the config in the shared folder - I don't have access to the destination server and it would make config changes more cumbersome.

To clarify, the hardcoded current path exists, but that's referring to a previous release, which doesn't have the puma config file.

**Comment by seuros** [comment]
You have a weird setup. 
```shared_path/../releases/``` might work for you.

**Comment by alauper** [comment]
releases isn't the folder, the timestamped folder inside of it is.  but the release path isn't created until after the puma:check, so what would I be pointing puma to?

you think it's weird to use the puma config in ./config/puma/ directly?

**Comment by seuros** [comment]
The puma check is run before the release folder is created but after the releases folder.

**Comment by alauper** [comment]
The puma config is in the current code base, which hasn't been deployed because the puma:check fails to find the file.  But the file is checked into the code base.

Are you pointing me to the releases (plural) folder?  Like you said, the release subfolder isn't created yet, so I'm not sure why 1. you're mentioning the releases folder.  2. why the puma check happens before the code has been checked out.
