### ISSUE TITLE
Request: Add Puma running user option

### ISSUE THREAD

**Issue by mcb** [seuros/capistrano-puma#115]
Before submitting a pull request for a feature we desperately need in our environment, I'd like to check if this is of any interest and would likely be merged, as I do not want to indefinitely keep a separate project from yours. 

We have the case that we have a multiple user setup, e.g. we have a user for deployment and one user that is allowed to run the application itself, however this running user does not have a ssh login, which is why I can't define a separate role for this user. 

I tried before to overwrite the tasks, however the concept of capistrano 3 does not support persisting roles as mentioned in https://github.com/capistrano/sshkit/issues/268.

I would suggest to implement an option to define a running user for puma and adapt this to match the existing code. However this is a major change and this is why I am asking prior submitting any pull request.

**Comment by seuros** [comment]
:+1:
