### ISSUE TITLE
uninitialized constant Puma::DSL::ActiveSupport (NameError)

### ISSUE THREAD

**Issue by dabit** [seuros/capistrano-puma#119]
After I added the `set :puma_init_active_record, true` to my `deploy.rb` and running `cap X puma:config` these few lines were added to my shared puma.rb file:

```
on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

This looks fine, except that Puma won't start and the logs are constantly showing the following error:

`uninitialized constant Puma::DSL::ActiveSupport (NameError)`

Maybe its missing a few requires?

**Comment by seuros** [comment]
do you run it in a bundle context ?

**Comment by dabit** [comment]
This is the command that ends up running so I'd say yes

    DEBUG [1c6b5157] Command: cd /var/web/app_dir/current && ( RACK_ENV=staging ~/.rvm/bin/rvm 2.1.6 do bundle exec pumactl -S /var/web/app_dir/shared/tmp/pids/puma.state restart )

**Comment by GabKlein** [comment]
This is happening when you are not using `preload_app!`

**Comment by a-b** [comment]
@GabKlein  
> This is happening when you are not using preload_app!

Is it possible to load rails without `preload_app!` at all?
Can you please elaborate why `uninitialized constant Puma::DSL::ActiveSupport ` happens?
Is that something to do with rails initialization specifics of app?
