### ISSUE TITLE
Maybe enable gzip in nginx config

### ISSUE THREAD

**Issue by nanowang** [seuros/capistrano-puma#121]
In recent version of sprockets, precompile wont generate .gz files.

So maybe we should use something like `gzip on` instead of `gzip_static on` in nginx config.

**Comment by bdewater** [comment]
@seuros I believe this change should be reverted because gzip support was reintroduced in Sprockets 3.5.0: https://github.com/rails/sprockets/commit/3abfe7877c2b127293a9e083cde66040134c730c

Gzipping assets for every request also introduces overhead that shouldn't be overlooked.

**Comment by seuros** [comment]
Sure thing.
