### ISSUE TITLE
ZSH / rbenv / bundler issue

### ISSUE THREAD

**Issue by chrise86** [seuros/capistrano-puma#136]
When running any puma related task, I get:

```
Using airbrussh format.
Verbose output is being written to log/capistrano.log.
00:00 puma:start
      using conf file /home/deploy/apps/app_name/shared/puma.rb
      01 bundle exec puma -C /home/deploy/apps/app_name/shared/puma.rb --daemon
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@serverip: puma exit status: 127
puma stdout: zsh:1: command not found: bundle
puma stderr: Nothing written

SSHKit::Command::Failed: puma exit status: 127
puma stdout: zsh:1: command not found: bundle
puma stderr: Nothing written

Tasks: TOP => puma:start
(See full trace by running task with --trace)
```

**Comment by seuros** [comment]
I don't use zsh personally, but a suspect that rbenv is not loaded or bundler not installed.

Do you have this plugin ?
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/rbenv/rbenv.plugin.zsh

**Comment by chrise86** [comment]
Just tried enabling it (didn't have it on before) and still the same :(

**Comment by chrise86** [comment]
Using the following seemed to fix:

    set :default_env, { path: '/usr/local/bin:/usr/local/rbenv/shims:/usr/local/rbenv/bin:$PATH' }

**Comment by seuros** [comment]
Please fill ticket in capistrano/rbenv.  This fix is a hack.

**Comment by seapy** [comment]
In my case this fix works.

```
set :rbenv_map_bins, %w{rake gem bundle ruby rails puma}
```

append puma to `rbenv_map_bins`
