### ISSUE TITLE
How to make puma restart when server reboot is occurred.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [seuros/capistrano-puma#137]
I have successfully deployed my rails application via capistrano and it is using Puma.

When I first deployed it, it is said `daemonizing`. Then It is only restarts puma when I deploy new versions of my app.

However, when server(Ubuntu Server 14.04) rebooted, Puma does not start by itself. I needed to redeploy my app and it said `daemonizing`.

My `deploy.rb` looks like this:

         set :application, 'myapp'
         set :repo_url, 'https://Path.To.My.Rep.git'

         set :linked_dirs, %w(
         bin log vendor/bundle public/system
         tmp/pids tmp/cache tmp/sockets
         )
         set :puma_bind, "tcp://0.0.0.0:8080"
         set :puma_state,      "/var/www/myapp/shared/tmp/pids/puma.state"
         set :puma_pid,        "/var/www/myapp/shared/tmp/pids/puma.pid"
         set :puma_access_log, "/var/www/myapp/shared/log/puma.error.log"
         set :puma_error_log,  "/var/www/myapp/shared/log/puma.access.log"

         set :whenever_identifier, ->{ "#{fetch(:application)}_#{fetch(:stage)}" }

         # This for carrierwave
         set :linked_dirs, fetch(:linked_dirs) + %w{public/system public/uploads}

I have two users in my server: `deployer` and `root`. I use `deployer` to deploy this app to server. `root` has ability to use `sudo` commands.

Do I need to add additional code for my `deploy.rb` file, in order to make my Puma on server able to restart after server is rebooted?

**Comment by seuros** [comment]
Yes that normal. You have to add a upstartd/systemd script to run your app on system reboot.

check out : https://github.com/puma/puma/tree/master/tools/jungle

**Comment by SuperMasterBlasterLaser** [comment]
When I try to run `sudo cp puma.conf puma-manager.conf /etc/init` it throws to me 
     cp: cannot stat ‘puma.conf’: No such file or directory
     cp: cannot stat ‘puma-manager.conf’: No such file or directory

**Comment by seuros** [comment]
you have to copy the file first form github: 
https://github.com/puma/puma/blob/master/tools/jungle/upstart/puma.conf
https://github.com/puma/puma/blob/master/tools/jungle/upstart/puma-manager.conf

**Comment by gowthamgts** [comment]
@seuros is this applicable to `systemd` also?

**Comment by SwathiSathish** [comment]
Hi. I need to restart puma through systemd after each deploy. So am using this command -> sudo systemctl restart puma in the deploy.rb file. But what is happening is, systemd puma will get killed and this command will run -> bundle exec pumactl -S /home/deploy/RTC/shared/tmp/pids/puma.state -F /home/deploy/RTC/shared/puma.rb restart. I dont want this to happen. Please advice and can anyone  help in writing the correct script in deploy.rb ?
