### ISSUE TITLE
jungle doens't respect puma_conf path

### ISSUE THREAD

**Issue by plentz** [seuros/capistrano-puma#144]
If the user have set in his `deploy.rb`:

``` ruby
set :puma_jungle_conf, '/etc/puma.conf'
```

I think we shouldn't create the default `shared/puma.rb` config. Instead, I think we should use the path set there.

Also, what do you think to change the default `puma_conf`to `config/puma.rb`, since it looks like to be the "default" folder for [puma's jungle](https://github.com/puma/puma/tree/master/tools/jungle/init.d#managing-the-jungle).

**Comment by joaomarcelo9393** [comment]
+1

I am using the "default" folder for [puma's jungle](https://github.com/puma/puma/tree/master/tools/jungle/upstart#conventions) (but using upstart), and I am having trouble changing the default `puma_conf`. 

I set `puma_conf` to `"#{current_path}/config/puma.rb"` but then I get `WARN puma.rb NOT FOUND!` when deploying. Of course it doesn't exist, but isn't it supposed to be created at the directory I specify in `puma_conf`? Did I misunderstand the purpose of `puma_conf`?
