### ISSUE TITLE
Confusion regarding config deployment

### ISSUE THREAD

**Issue by pratik60** [seuros/capistrano-puma#155]
It seems like every time I change the config, I must run

`cap staging puma:config` # Insert your environment here

otherwise the changes don't take effect. This seems highly unintuitive to me, and I spent 2-3 hours trying to wonder what is happening. In fact, I only resorted to this as a debugging technique.

I would ideally assume that changing things in deploy.rb should have the necessary effect automatically, but for me it doesn't and I need to run this after every change in puma config. (agreed, it isn't often) 

Is this expected behaviour? If so, can I make a quick pr and add it to the readme? If it isn't, can you please tell me what am I doing wrong?

**Comment by MetricMike** [comment]
I believe this is intended behavior and if you read what puma:start I think it makes a bit more sense: 

[puma.rake#L39-L62](https://github.com/seuros/capistrano-puma/blob/ce76a49c60e5596b82880dbd717f821bbaaf6d13/lib/capistrano/tasks/puma.rake#L39-L62)
```ruby
  desc 'Setup Puma config file'
  task :config do
    on roles(fetch(:puma_role)) do |role|
      template_puma 'puma', fetch(:puma_conf), role
    end
  end

  desc 'Start puma'
  task :start do
    on roles (fetch(:puma_role)) do |role|
      puma_switch_user(role) do
        if test "[ -f #{fetch(:puma_conf)} ]"
          info "using conf file #{fetch(:puma_conf)}"
        else
          invoke 'puma:config'
        end
        within current_path do
          with rack_env: fetch(:puma_env) do
            execute :puma, "-C #{fetch(:puma_conf)} --daemon"
          end
        end
      end
    end
  end
```

If capistrano-puma detects a file at `:puma_conf`, there isn't a way to tell if that was supplied by the user or built from `deploy.rb`. So it takes the safe route and assumes that it was supplied by the user unless you explicitly override with `cap puma:config`

The commit that introduced this behavior is https://github.com/seuros/capistrano-puma/commit/6d210b810b8f0eff732a922abf76473104321b57, and while that did make it into the CHANGELOG (it's v0.8.2) a README change was not included.

I think it's probably best to point `:puma_conf` to current_path by default and rewrite that section of the README to inform users who want to supply their own config file.
