### ISSUE TITLE
production logs with rails5

### ISSUE THREAD

**Issue by razorcd** [seuros/capistrano-puma#158]
We added `capistrano-puma` to our already `capistrano`, `puma`,  `rails 5` app and noticed the **`production.log` file lost the default rails 5 colors and are more verbose**.

We have same configs in `staging` and `production` except the `environment` name, of course. In staging we have rails 5 colors and more compact data. 

Why are production logs different with same configs? I can't find anything in the gems code that changes that. We only added `capistrano-puma` configs today.

Anybody experienced this?

**Comment by seuros** [comment]
Strange, this gem is not even loaded production.
