### ISSUE TITLE
Question about nginx config defaults

### ISSUE THREAD

**Issue by heidar** [seuros/capistrano-puma#162]
The default nginx template in this project is great, I've never had to change any of it. However, I noticed one thing I don't really understand:

    location ~ \.(php|html)$ {
      return 405;
    }

This is at the bottom of the file. What's the purpose of this? And why not 404 instead of 405?

Thanks!

**Comment by seuros** [comment]
I think this block can be removed. 
.html should not blocked as we can't use static files.

**Comment by heidar** [comment]
Thanks, I just wanted to double check in case I was missing something it was being used for. I've removed it in my projects. Should we also get rid of it in the config template in this project?

**Comment by ignisf** [comment]
This breaks access to the default error files in Rails' `public/` directory.
