### ISSUE TITLE
Reload dotenv file on restart

### ISSUE THREAD

**Issue by EvAlex** [seuros/capistrano-puma#164]
After deploy puma service is restarted. But if `dotenv-rails` is used, new env vars values are not loaded. I resolved this by manually adding dotenv update code to `shared/puma.rb`:

```ruby
require 'dotenv'

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/var/www/junglefox/backend/current/Gemfile"
  ENV.update Dotenv::Environment.new('.env.staging') # BTW can i retrieve this 'staging' string here to make code more generic?
end
```

This is workaround, yes. But is there another way of doing this? Maybe new capistrano config value to handle dotenv automatically. Maybe something else. At least add a notice about this problem to docs, because I spent some time debuggin the issue.

**Comment by seuros** [comment]
Yes. copy this file https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/templates/puma.rb.erb to config/deploy/templates/puma.rb.erb and modify it to your need.

then run puma:config. 

Puma will use the file instead of the stock one.

**Comment by EvAlex** [comment]
Thanks, that's a clean way of doing it! I wish this repo had a wiki with this recommendation!

**Comment by seuros** [comment]
@EvAlex could you start it ?

**Comment by EvAlex** [comment]
Yes, I can. Should I fork and make PR? I doubt that if I create wiki in my fork, it will transfer here in a PR. I think I will just stick to README.md file.

**Comment by seuros** [comment]
You can edit this Repo PR without any PR.
