### ISSUE TITLE
restart terminated instance

### ISSUE THREAD

**Issue by u007** [seuros/capistrano-puma#167]
hi,

i deployed with trace and ended with puma:restart,
but the instance died without starting back.
ive to issue puma:start to have it back up.
it seems to happen 50% of the time.
here is the trace:

INFO [69906938] Running /usr/local/rvm/bin/rvm 2.2.4-dev do bundle exec pumactl -S /home/name/rails-stg/shared/tmp/pids/puma.state restart as name@146.148.11.198
DEBUG [69906938] Command: cd /home/name/rails-stg/current && ( export RACK_ENV="staging" ; /usr/local/rvm/bin/rvm 2.2.4-dev do bundle exec pumactl -S /home/name/rails-stg/shared/tmp/pids/puma.state restart )
DEBUG [69906938] 	Command restart sent success
INFO [69906938] Finished in 1.888 seconds with exit status 0 (successful).

using:
rails (5.0.0.beta3)
capistrano (3.5.0)
capistrano3-puma (1.2.1)
capistrano-rails (1.1.6)
puma (2.16.0)

thank you

**Comment by u007** [comment]
sorry wrong thread ><

**Comment by u007** [comment]
o sorry im at correct github :)

**Comment by seuros** [comment]
check your  log file, the error is there.
