### ISSUE TITLE
Close connections

### ISSUE THREAD

**Issue by mchicote** [seuros/capistrano-puma#169]
Hi
I've noticed that puma's documentation says:

> If you're preloading your application and using ActiveRecord, it's recommended that you close any connections to the database here to prevent connection leakage: 
```
# config/puma.rb
before_fork do
  ActiveRecord::Base.connection_pool.disconnect!
end
```

I've looked around this plugin but I don't think this is part of the configuration file. Shouldn't this be included in puma.rb.erb template file? Do I need to do this manually?

Thanks!

**Comment by seuros** [comment]
ok let add it.

**Comment by mchicote** [comment]
@seuros do you want me to do a PR or do you want to take care of it by yourself?

**Comment by seuros** [comment]
@mchicote go ahead with a PR against this PR #168 . 💚

**Comment by mchicote** [comment]
I'm not sure what you mean by "PR against this PR" but I opened a PR against v1 #170 
Let me know if this works or if you need me to do something else.

**Comment by seuros** [comment]
that it, thanks.
