### ISSUE TITLE
sudo login doesn't work

### ISSUE THREAD

**Issue by dryaf** [seuros/capistrano-puma#172]
How are you even able to use this?

set :pty, true

entering the password shows plain text and does nothing after a return

does this only work on linux? I'm on a mac

**Comment by focused** [comment]
I switched off password for the time of setup:

```
$ sudo nano /etc/sudoers
```

```
deployer ALL=(ALL) NOPASSWD:ALL
```

After setup switch on again.

**Comment by juansecaro** [comment]
Same problem, tried using visudo without solution
