### ISSUE TITLE
Doesn't inherit multistage configuration

### ISSUE THREAD

**Issue by benpolinsky** [seuros/capistrano-puma#179]
Using Capistrano 3

In a multistage environment, I've found that each stage does not pick up on config variables like `:puma_pid` in deploy.rb.

Aren't the various stages supposed to inherit variables from deploy.rb?

I'll try to reproduce on an app specifically made for this problem when I have a second.

**Comment by seuros** [comment]
i could not reproduce this bug. i have configs in both deploy.rb and production.rb
