### ISSUE TITLE
JRUBY_OPTS not taken into consideration

### ISSUE THREAD

**Issue by marcoschicote** [seuros/capistrano-puma#183]
Hi
I use puma with jruby and have configured my deploy.rb like this:

```
set :jruby_opts, "-J-Xmx4G -J-Xms4G -J-XX:PermSize=1024M -J-XX:MaxPermSize=2048m"
set :default_env, { JRUBY_OPTS: "-J-Xmx4G -J-Xms4G -J-XX:PermSize=1024M -J-XX:MaxPermSize=2048m" }
```

However, after deploying the JRUBY_OPTS are not taken into consideration. If I do `ps aux | grep java` I don't see the parameters I configured.

Is this a bug? Am I doing this wrong?

Thanks!

**Comment by zben** [comment]
@mchicote did you figure a way out?

**Comment by mchicote** [comment]
Hi @zben
I'm not quite sure but I don't think we did. I left the project and last I heard it had been cancelled.
