### ISSUE TITLE
puma restart on deployment does not picks the latest release

### ISSUE THREAD

**Issue by RahulMahale** [seuros/capistrano-puma#189]
We observed number of times, after deployment puma is restarted, We see puma  restarted successfully.

But it doesnt picks the code from latest release and we have to manually restart it.

Finally we decided to handle it using init script to restart puma.

Is it only me facing this  issue ?

**Comment by Fudoshiki** [comment]
same

**Comment by seuros** [comment]
What version of puma do you use ?

**Comment by RahulMahale** [comment]
@seuros  we use `puma 3.6.0` and `capistrano-puma 1.2.1`

**Comment by seuros** [comment]
try to use capistrano-puma 3.0.2+ . 
can you show me the puma config that you have in deploy.rb ?

**Comment by vitalyliber** [comment]
Thanks @seuros. 
I had the same issue with capistrano-puma 3.1.0 and capistrano 3.8.1. 
But with 3.0.2 I haven't problems.

**Comment by ysksn** [comment]
same :cry: 
`puma:restart` not working with `capistrano3-puma 3.1.0` and `capistrano 3.8.1`.
`capistrano3-puma 3.0.3` and `capistrano 3.8.1` are fine though.
