### ISSUE TITLE
shared_path not working

### ISSUE THREAD

**Issue by ryush00** [seuros/capistrano-puma#197]
I'm using capistrano 3.7.2.

If I set config with ```#{shared_path}```, 

```
set :puma_bind, "unix://#{shared_path}/tmp/sockets/puma2.sock"    #accept array for multi-bind
```

and ```cap production puma:config```, and it became

```
bind 'unix:///tmp/sockets/puma.sock'
```

I was stucked for this problem about 4 hours.

I think ``````#{shared_path}`````` in ```deploy.rb``` is not working. Thanks.

**Comment by seuros** [comment]
use a proc
set :puma_bind, -> { "unix://#{shared_path}/tmp/sockets/puma2.sock" }

**Comment by ryush00** [comment]
Sorry. I edited original comment.'''#{shared_path}''' became empty.

**Comment by seuros** [comment]
you have something wrong with your code.
