### ISSUE TITLE
Use puma plugins in deploy.rb

### ISSUE THREAD

**Issue by hanhdt** [seuros/capistrano-puma#199]
Hi,

Anyone can tell me what is right way to use `set :puma_plugins`?

I have implemented to `set :puma_plugins, [:tmp_restart]` that allow puma to be restarted by `rails restart` command. Is it ok?

Thanks you.

**Comment by seuros** [comment]
Yes. You have to run : `puma:config` to refresh your puma.rb remotely.

**Comment by hanhdt** [comment]
Yes, thank you.
