### ISSUE TITLE
Ruby Gems Outdated

### ISSUE THREAD

**Issue by leeh** [seuros/capistrano-puma#202]
Would it be possible to push actual releases to https://rubygems.org/gems/capistrano3-puma ?  

It's annoying to have to code an explicit github dependency, especially since I no need to add a specific ref to stay at 2.0, since testinh 3.0.0 broke my build.

**Comment by seuros** [comment]
Alright.

**Comment by seuros** [comment]
@leeh Release both version. Can you tell me how did the build break ?
