### ISSUE TITLE
`puma:monit:config` doesn't work in 3.0.0

### ISSUE THREAD

**Issue by johnmcdowall** [seuros/capistrano-puma#203]
Running the `puma:monit:config` task errors out with an undefined method to `template_puma`. 

Looks like the monit plugin didn't get a `PumaCommon` inlclude: https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/puma/monit.rb#L2

Adding this leads to other errors though. Seems like no one has tested this task before releasing 3.0.0.

**Comment by seuros** [comment]
@johnmcdowall Fixed. Thank you for the report
