### ISSUE TITLE
puma:config task not picking up from local templates

### ISSUE THREAD

**Issue by elfenars** [seuros/capistrano-puma#208]
## What's supposed to happen:

The task `puma:config`, according to the README is supposed to generate a template for you and upload it to your app server, but also in the code there's some logic that _should_ allow the user to have their own template somewhere locally and if so, the task _should_ pick up on the users local template and use that instead of generating a new one

The logic for this can be found in [puma.rb:34#template_puma](https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/puma.rb#L34)

## The problem:

The logic in said lines would work, but since the `from` parameter is being hardcoded as `puma.rb` previously in:

```ruby
def upload_puma_rb(role)
  template_puma 'puma.rb', fetch(:puma_conf), role
end
```

The local template will *never* be considered, since the array of possible paths also contains an extension `.rb`

## Solution:

Remove the `.rb` extension from the `upload_puma` method.

## Better solution:

Allow the user to specify a template name when calling the `puma:config` task.

**Comment by seuros** [comment]
Can you explain your use case ?

**Comment by elfenars** [comment]
I already had my puma setup ready, therefore I already had my own puma.rb file which I don't really want to change or move to settings inside my deploy files.

But capistrano has a bug when using pumactl, which this gem solves by adding some nice logic to the process of start/restart (and other features) that I don't wanna port to my app.

So I want to use the gem, but be able to keep my own puma.rb file, which is exactly what the purpose of that method is intended to do, if I read correctly, but it has this bug that doesn't allow me to use my own puma.rb...
