### ISSUE TITLE
A possibility to not load hooks should be made available

### ISSUE THREAD

**Issue by thomasdarde** [seuros/capistrano-puma#210]
Just adding 
`require 'capistrano/puma'`
to the Capfile loads hook puma:restart

It's impossible to unload it.

It would be good to be able to write :
`install_plugin Capistrano::Puma, load_hooks: false`

**Comment by seuros** [comment]
I will issue fix

**Comment by thomasdarde** [comment]
Thanks !
In the end, for the record I've changed some
`after  'deploy:finished'`
in
`before 'puma:restart'`

And could make my deployment happy again

**Comment by seuros** [comment]
check https://github.com/seuros/capistrano-puma/pull/212 

If it work for you without the hack. i will release the new version

**Comment by thomasdarde** [comment]
Amazing,

It's working , but your documentation should state:

`install_plugin Capistrano::Puma, load_hooks: false`
instead of :

`install_plugin Capistrano::Puma, false`

**Comment by seuros** [comment]
Fixed .

**Comment by zeitnot** [comment]
@seuros after I set `install_plugin ::Capistrano::Puma, load_hooks: false` it says `NameError: uninitialized constant Capistrano::Puma`. Puma's tasks are working. I mean capistrano can load them but weirdly this error happens.

**Comment by zeitnot** [comment]
@seuros upgrading both capistrano and capistrano3-puma versions fix my problem.
