### ISSUE TITLE
Upgrade to 3.1.0 caused error “Don't know how to build task 'start'”

### ISSUE THREAD

**Issue by slavikdev** [seuros/capistrano-puma#213]
Hello.
I’ve recently upgraded from 3.0.3 to 3.1.0 and got the following error:
```
Don't know how to build task 'start' (see --tasks)
```

This config worked on 3.0.3:
```ruby
require 'capistrano/puma'
install_plugin Capistrano::Puma::Workers
```

Now with 3.1.0 I got it working like this:
```ruby
require 'capistrano/puma'
install_plugin Capistrano::Puma
install_plugin Capistrano::Puma::Workers
```

So basically `install_plugin Capistrano::Puma` is required. 
My issue is resolved, I just wanted to share in case someone else stumbles on it.

**Comment by seuros** [comment]
@slavikdev This change was introduced to fix #210 #204 .  
Not loading the hooks was a feature before and we had a regression in 3.0.0 . 

Thanks for opening this issue.

**Comment by hjoe** [comment]
Oh man, I've been working on this problem forever. Thanks a ton!

**Comment by Digi-Cazter** [comment]
Awesome, thanks, found this just before I ended up down the rabbit hole trying to figure this out.
