### ISSUE TITLE
Double bundle exec when starting puma causes incorrect puma launcher load: LoadError: cannot load such file -- puma/state_file

### ISSUE THREAD

**Issue by engeen** [seuros/capistrano-puma#214]
00:00 puma:start                                                                               
      using conf file /home/deployer/insurance/shared/puma.rb                                  
      01 bundle exec bundle exec puma -C /home/deployer/insurance/shared/puma.rb --daemon      

What's the reason?

**Comment by engeen** [comment]
Using this:
require 'capistrano/puma'
install_plugin Capistrano::Puma 

This leads for double calling for puma.rake, so it requires capistrano/puma.rb twice as well as it requires twice capistrano/bundler which binds "bundle exec" prefix twice

**Comment by engeen** [comment]
It really works fine without install_plugin Capistrano::Puma

**Comment by seuros** [comment]
@engeen install_plugin Capistrano::Puma is only for the lastest version of the gem. I think you have previous version 3.0.x

**Comment by dsandstrom** [comment]
@seuros The readme for v3.0.3 shows the `install_plugin` instructions so it's confusing.

https://github.com/seuros/capistrano-puma/tree/v3.0.3
