### ISSUE TITLE
Allow SSL certificates to be somewhere else than /etc/ssl/certs/

### ISSUE THREAD

**Issue by wynksaiddestroy** [seuros/capistrano-puma#217]
I'm using Let's Encrypt to create my SSL certificates. When using the recommended method by running [Certbot](https://certbot.eff.org) the certificates are placed in `/etc/letsencrypt/live/www.foobar.me/` for example.
Unfortunately `capistrano-puma` expects the certificates to be located in `/etc/ssl/certs/` and `/etc/ssl/private/`.
Wouldn't it be useful to have an option to explicitly set an absolute path for the certificates?

**Comment by egoens** [comment]
@wynksaiddestroy Did you find an alternative release process or a work around for still using `capistrano-puma` as a release tool? I'm about to be in the situation.

**Comment by wynksaiddestroy** [comment]
@egoens: You can customize the nginx configuration by running `rails generate capistrano:nginx_puma:config` and then changing the relevant parts of `config/deploy/templates/nginx_conf.erb` to reflect the acutal place of your certificates.
Actually I'm think about creating a pull request, so you can set the path for your certificates in your `deploy.rb`.

**Comment by seuros** [comment]
@wynksaiddestroy i will merge that PR.

**Comment by wynksaiddestroy** [comment]
@seuros Please hava a look at #221 😊
