### ISSUE TITLE
puma:monit:config failure

### ISSUE THREAD

**Issue by shredder-rull** [seuros/capistrano-puma#219]
cap production puma:monit:config
rvm 1.28.0 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
ruby-2.3.3
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
00:00 puma:monit:config
      Uploading /tmp/monit.conf 100.0%
Warning: `execute' should be wrapped in an `on' scope in /Users/macbookpro/.rvm/gems/ruby-2.3.1/gems/capistrano-3.8.0/lib/capistrano/dsl.rb:38.

  task :example do
    on roles(:app) do
      execute 'whoami'
    end
  end

(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@replaced.us-west-2.compute.amazonaws.com: undefined method `execute' for main:Object

NoMethodError: undefined method `execute' for main:Object

Tasks: TOP => puma:monit:config
(See full trace by running task with --trace)

**Comment by ivanovaleksey** [comment]
The same issue for me

**Comment by lidashuang** [comment]
How to solve this?

**Comment by ivanovaleksey** [comment]
@lidashuang As you can see it is already solved on master branch.
You can wait for the new gem version or use master branch.
