### ISSUE TITLE
Please add new variable for puma monit deploy user

### ISSUE THREAD

**Issue by bombazook** [seuros/capistrano-puma#225]
Puma::Monit uses same role as Puma app server deployment itself (:puma_role), but expects one of 2 choices:
1. Sudo for puma deployment user (which is inconvenient way for app server deployment according to http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/)
2. User-level monit script without sudo (which is inconvenient way because of monit docs mentioning monit as a service running by root)

I would suggest to add separate role for monit deployment and make it the same as :puma_nginx by default (which has same sudo requirements)

**Comment by bombazook** [comment]
Looks like monit config templating task should be updated to something like
```ruby 
startup_role = roles(fetch(:puma_role)).first
git_plugin.template_puma 'puma_monit.conf', "#{fetch(:tmp_dir)}/monit.conf", startup_role
```

**Comment by seuros** [comment]
why first ?

**Comment by bombazook** [comment]
I suppose the idea is to not run any web app by sudoer. Еspecially passwordless one.
http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/#authorisation

**Comment by seuros** [comment]
But monit need to get installed in each server. It can't monitor remote process.

**Comment by bombazook** [comment]
Sure, but you can stop it's http interface after configuring so the only process involved in http/s will be puma started under plain user without sudo.

**Comment by bombazook** [comment]
So there could be 2 users:
1. configurator user with sudo that pushes nginx and monit config
2. deploy user without sudo that makes all other stuff
