### ISSUE TITLE
Nginx Websocket (action_cable) support 

### ISSUE THREAD

**Issue by ccastillop** [seuros/capistrano-puma#233]
### Problem

At Rails 5, with action_cable and Nginx, websocket is not supported:

`Started GET "/cable" for 127.0.0.1 at 2016-07-31 21:04:47 -0400
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: , HTTP_UPGRADE: )
Finished "/cable/"[non-WebSocket] for 127.0.0.1 at 2016-07-31 21:04:41 -0400`

### Solution

Just add some lines to nginx.conf.erb template. It could be default?

At nginx.conf.erb

`  # enables WS support
  location /cable {
    proxy_pass http://puma_<%= fetch(:nginx_config_name) %>;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }`

**Comment by seuros** [comment]
Hi.
It can't be default because Puma and this gem can be used with other frameworks (sinatra, padrino, ..) and not every project needs action_cable.

You can however use the generator to copy the template in your project and change it as you want.

Thank you for the report.
