### ISSUE TITLE
rvm1-capistrano3 compatibility

### ISSUE THREAD

**Issue by sriedel** [seuros/capistrano-puma#239]
I'm using the rvm1-capistrano3 gem, since the capistrano-rvm gem doesn't work for me and seems to be no longer maintained (see https://github.com/capistrano/rvm/issues/83). 

As soon as I added `install_plugin Capistrano::Puma` line to my Capfile, capistrano could no longer invoke bundler correctly, since the rvm wrapper wasn't being used anymore.

Looking at the code both in rvm1-capistrano3 and here, both are accessing the rvm_bin_maps variable, which seems to be the main point of contention. However I'm not sure as to why, since rvm1-capistrano3 should be loading on demand, if I read the code correctly (https://github.com/rvm/rvm1-capistrano3/blob/master/lib/rvm1/tasks/capistrano3.rake#L41) and capistrano-puma just appends puma and pumactl to the variable. I suspect some order-of-execution issue.

The only thing I've got to actually work is adding `set :rvm_map_bins, [ 'rake', 'gem', 'bundle', 'ruby', 'puma', 'pumactl' ]` to my deploy.rb file. Not very clean, but Works For Me (TM). 

Maybe you can add a pointer in the setup documentation for others having similar issues.

**Comment by sinthetix** [comment]
Having the same issue, unfortunately. And `set :rvm_map_bins` did not work for me :/
