### ISSUE TITLE
Custom puma.rb content

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [seuros/capistrano-puma#240]
Hi @seuros,

Thank you for the nice work developing the gem!
I was trying to find out how could I add custom config lines to the generated puma.rb.
Is there a way to do this? Was not able to find.

Thank you in advance!

**Comment by seuros** [comment]
The gem will search in these path. https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/puma.rb#L35-L43

You can put a custom file there.

just be sure to run puma:config if the file was already uploaded.

**Comment by sergey-koba-mobidev** [comment]
Thank you, will try!
