### ISSUE TITLE
Monit fails without sudo

### ISSUE THREAD

**Issue by kyrofa** [seuros/capistrano-puma#241]
When setting `puma_monit_use_sudo` to false (default for everything else) I get the following failure when deploying:

```
00:18 puma:monit:config
      Uploading /tmp/monit.conf 100.0%
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@mydomain.com: Exception while executing as deploy@mydomain.com: Exception while executing on host #<SSHKit::Host:0x000000014fb978>: undefined local variable or method `backend' for #<SSHKit::Backend::Netssh:0x000000014fb568>
Did you mean?  background
```

When `puma_monit_use_sudo` is true I get an error about no askpass, which is expected because the `deploy` user cannot sudo on my box, so it seems it runs as expected. Something different seems to happen when sudo is not used.

**Comment by saten** [comment]
I believe this is somehow related to having a custom ssh_command (e.g. because deploying through a gateway). Could you confirm that?

**Comment by jpatters** [comment]
I am having this issue and do not have a custom ssh_command (that I know of). I solved this by reverting the change made here: https://github.com/seuros/capistrano-puma/commit/642f615b1b318cf1ccf19d325a211b246fc252b1#diff-b1d6807d05f4f0f45dc4c0aa024eeee0L27
