### ISSUE TITLE
Don't know how to build task 'puma:config' (see --tasks)

### ISSUE THREAD

**Issue by BorisBresciani** [seuros/capistrano-puma#253]
Hey,

I have this error:
`Don't know how to build task 'puma:config' (see --tasks)`

When I type the command:
`bundle exec cap production puma:config`
or
`cap production puma:config`

Gemfile:
`group :development do`
  `gem 'capistrano'`
  `gem 'capistrano-rails'`
  `gem 'capistrano-rvm'`
  `gem 'capistrano3-puma'`
`end`

Capfile
`require 'capistrano/puma'`
`install_plugin Capistrano::Puma`
`require 'capistrano/puma/nginx'`
`install_plugin Capistrano::Puma::Nginx`

Command:
`cap -T | grep -i puma`
Return nothing

Thanks you for your help !

**Comment by BorisBresciani** [comment]
Fix: I put the "capfile" file in the wrong place

**Comment by cuongncFramgia** [comment]
@BorisBresciani could you plz tell me where do u put capfile?

**Comment by thanhtt** [comment]
From Capitrano ver 3.7.2 to latest, Puma not auto require capistrano/puma
Please add this line below `require "capistrano/puma` and try again
```install_plugin Capistrano::Puma```
