### ISSUE TITLE
puma:nginx_config fails

### ISSUE THREAD

**Issue by DaniG2k** [seuros/capistrano-puma#254]
When I type `cap production puma:nginx_config` I am seeing the following error:

```
rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
ruby-2.4.1
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
00:00 puma:nginx_config
      Uploading /tmp/nginx_my_app 100.0%
      01 sudo mv /tmp/nginx_my_app /etc/nginx/sites-available/my_app
      01 sudo
      01 :
      01 no tty present and no askpass program specified
      01
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as dani@my_app.com: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: sudo: no tty present and no askpass program specified
```

I saw some people online said to add `set :pty, true` in deploy.rb. However, this does not fix the problem. I am prompted for a password but if I enter it, it displays in plain text and hitting enter does absolutely nothing.

What is the proper fix for this?

**Comment by seuros** [comment]
You need to have passwordless sudo for that deploy user.

**Comment by DaniG2k** [comment]
I've added the following to my `/etc/sudoers` file

`dani ALL=(ALL) NOPASSWD:ALL`

but running the aforementioned command still returns `no tty present and no askpass program specified`.

**Comment by seuros** [comment]
login into the server and do `sudo ls` . i suspect that the setting didn't apply correctly (check if it still ask for password)

**Comment by DaniG2k** [comment]
Hmm `sudo ls` works perfectly well. So does `sudo apt-get update` or any other command I run with sudo

**Comment by Nic062** [comment]
Same problem ! I don't know what to do 😔

**Comment by tanhit243** [comment]
you must add  the following code after  `%sudo   ALL=(ALL:ALL) ALL`
```
# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

your_user  ALL=(ALL) NOPASSWD: ALL

```
https://www.simplified.guide/linux/enable-passwordless-sudo
