### ISSUE TITLE
NameError: uninitialized constant Capistrano::Puma

### ISSUE THREAD

**Issue by iit2011081** [seuros/capistrano-puma#260]
Capistrano puma is giving error. Following is the content of my Capfile 

```
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/bundler'
require 'capistrano/rvm'
require 'capistrano/rails/assets' # for asset handling add
require 'capistrano/rails/migrations' # for running migrations
require 'capistrano/puma'
require 'capistrano/rake'

install_plugin Capistrano::Puma
# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

When I run cap -T it is showing me "NameError: uninitialized constant Capistrano::Puma". When I remove "install_plugin Capistrano::Puma" from Capfile, it is working fine.

**Comment by seuros** [comment]
You probably have an old version of the gem.

**Comment by iit2011081** [comment]
I am using capistrano3-puma-1.2.1

**Comment by iit2011081** [comment]
My gemfile is as
```
group :development do
    gem 'capistrano'
    gem 'capistrano3-puma'
    gem 'capistrano-rails', require: false
    gem 'capistrano-bundler', require: false
    gem 'capistrano-rake', require: false
    gem 'capistrano-rvm'
end
```

**Comment by seuros** [comment]
You need to update it. 
bundle update capistrano3-puma

**Comment by iit2011081** [comment]
Thanks, now working..

**Comment by thomaspatricksteven** [comment]
Just want to spell this out for anyone who skipped over this post when trying to resolve this issue.

Check your Gemfile. You need `capistrano3-puma`  NOT `capistrano-puma`. Make sure you have that three.

Thanks

**Comment by daz** [comment]
I needed to change:

    gem "capistrano3-puma", "~> 1.2"

for this:

    gem "capistrano3-puma", github: "seuros/capistrano-puma"

**Comment by seuros** [comment]
@daz  you can also use released version 

gem "capistrano3-puma", "~> 5.2"

or latest 
gem "capistrano3-puma", "~> 6.0.0.beta"

**Comment by robot-den** [comment]
For those who came here with `uninitialized constant Capistrano::Puma (NameError)`
You need to use `gem "capistrano3-puma", github: "seuros/capistrano-puma"`

If you use just `gem "capistrano3-puma"` it installs a very old version - `capistrano3-puma (1.2.1)`
