### ISSUE TITLE
config tasks not using deploy folder from stage file

### ISSUE THREAD

**Issue by javinto** [seuros/capistrano-puma#261]
I have a lot of different config/deploy/stage files. Each stage file sets the :deploy_to variable. That is necessary as I have to set the full deploy path. Like so:

config/deploy/puma-test.rb
`set :deploy_to, "/var/www/vhosts/puma-test.nl/rails"`

In config/deploy.rb there is no set :deploy_to line.

Unfortunately the plugin tasks do not listen to the stage files. When I deploy I get:

> 00:04 puma:check
>       WARN  puma.rb NOT FOUND!
> (Backtrace restricted to imported tasks)
> cap aborted!
> SSHKit::Runner::ExecuteError: Exception while executing as test@puma-test.nl: scp: /var/www/shared/config/puma/production.rb: No such file or directory

when I copy the set :deploy_to line from the stage file to my config/deploy.rb it works. But that is not the expected behavior.

**Comment by swissmadekzu** [comment]
I have sort of solved the issue by putting the following config line in the stages files.

`set :puma_conf, "#{shared_path}/config/puma.rb"`
