### ISSUE TITLE
Gemfile not found

### ISSUE THREAD

**Issue by rockandruby** [seuros/capistrano-puma#263]
releases/20180405092800/Gemfile not found (Bundler::GemfileNotFound)

> group :development do
>   gem 'capistrano', '~> 3.10', require: false
>   gem 'capistrano-rails', '~> 1.3', require: false
>   gem 'capistrano-rvm', require: false
>   gem 'capistrano-bundler', '~> 1.3', require: false
>   gem 'capistrano3-puma', require: false
> end

**Comment by seuros** [comment]
I need more details then this.

**Comment by rockandruby** [comment]
@seuros what exactly?

**Comment by rockandruby** [comment]
was my issue in gem 'god' usage
