### ISSUE TITLE
Is there monit config template generator analogical to what capistrano-sidekiq has?

### ISSUE THREAD

**Issue by ypadlyak** [seuros/capistrano-puma#268]
If there is no, I could just copy the template from the repo, but how do I override to use it?

**Comment by faizalzakaria** [comment]
Hi @ypadlyak ,

From the code,

https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/tasks/monit.rake#L8
https://github.com/seuros/capistrano-puma/blob/81647bc8402ff1cb485e81d9ec803dfec31aa851/lib/capistrano/puma.rb#L41-L45

There are few ways to override it.
Ex. Create a template file, with exact file name, `puma_monit.conf.erb` in your app root dir, `config/deploy/templates/puma_monit.conf.erb`.

I hope this help.
