### ISSUE TITLE
cap puma:config, avoiding hell for future users

### ISSUE THREAD

**Issue by webzorg** [seuros/capistrano-puma#269]
Hey all, I have had a horrible day yesterday because it turns out `cap puma:config` command generates config file for puma _Without_  `port ENV.fetch("PORT") { 3000 }` which was breaking my configuration and I took 2-3 hours to figure it out. Port option is a default in rails config/puma.rb and would be great if it got included into the config file generated by `cap puma:config`. Thanks allot in advance.

**Comment by patrykk21** [comment]
What about
```
set :puma_bind, ["unix://#{shared_path}/tmp/sockets/puma.sock", "tcp://0.0.0.0:#{ENV.fetch('PORT', 3000)}"]
```
?
