### ISSUE TITLE
Possibility to run multiple confs for the same application

### ISSUE THREAD

**Issue by TeamNautilus** [seuros/capistrano-puma#271]
In our production system we have an application that serves two different country according to an environment variable.
We would like to be able to configure the number of workers/threads for the different configurations and, obviously, set a different env variable.
Is it possible to run and manage two puma cluster as we described with capistrano-puma?
We've tried to fork the project and implement a multi confs handling (as a spike and in a very very ugly and hackish way ) but we are not sure if it's the best solution (you can see it [here](https://github.com/teamnautilus/capistrano-puma)).
Is there any other way to get the same result? Do you think it could be a useful feature to add in the future?

**Comment by AlexanderZaytsev** [comment]
> In our production system we have an application that serves two different country according to an environment variable.
> We would like to be able to configure the number of workers/threads for the different configurations and, obviously, set a different env variable.
> Is it possible to run and manage two puma cluster as we described with capistrano-puma?
> We've tried to fork the project and implement a multi confs handling (as a spike and in a very very ugly and hackish way ) but we are not sure if it's the best solution (you can see it [here](https://github.com/teamnautilus/capistrano-puma)).
> Is there any other way to get the same result? Do you think it could be a useful feature to add in the future?

Did you find a solution?

**Comment by TeamNautilus** [comment]
Sorry, no news. At the moment we do not work with Puma and now we have only one application with one country running.
