### ISSUE TITLE
Why is puma always running as a daemon?

### ISSUE THREAD

**Issue by cedv** [seuros/capistrano-puma#274]
It seems that the :puma_daemonize setting is ignored and puma always run as a daemon.

Looking in the source code, I can see this line in the start task:

`execute :puma, "-C #{fetch(:puma_conf)} --daemon"`

`--daemon` is just hard coded there. Very puzzling...

Is there any way I can prevent the `puma:start` task from launching puma as a daemon? Thanks.

**Comment by seuros** [comment]
because capistrano will never finish if the process don't exit.  Maybe you want to start it using upstart or systemd
