### ISSUE TITLE
Does not work with Ruby 2.6.3

### ISSUE THREAD

**Issue by Qqwy** [seuros/capistrano-puma#289]
On Ruby 2.6.3, following the steps in the README exactly, and even using projects that were able to build on earlier ruby versions, I get a `NameError: Constant not defined Capistrano::Puma` upon attempting to call `cap production deploy`.

**Comment by lalusaud** [comment]
Same here. Got this with ruby 2.6.2.

`(Backtrace restricted to imported tasks)
cap aborted!
NameError: uninitialized constant Capistrano::Puma
/xx/xxx/Capfile:11:in `<top (required)>'
(See full trace by running task with --trace)`

**Comment by tripledub** [comment]
@lalusaud what OS are you using? It does not work for me on MacOS 10.15.3, but if I open up my project in Vagrant (Xenial) all is good. In both cases I'm using rbenv ruby ruby 2.6.5

**Comment by danieldraper** [comment]
Related to https://github.com/seuros/capistrano-puma/issues/291 still happening in Ruby 2.6.6
