### ISSUE TITLE
Ruby 2.6.5: Cannot load such file -- capistrano/puma

### ISSUE THREAD

**Issue by webinti** [seuros/capistrano-puma#291]
Hello,

I'm running ruby 2.6.5 on MacOs 10.15.1

My capfile is:
```
#capfile
require "capistrano/rbenv"
require "capistrano/rails"
require "capistrano/puma"
require "capistrano/puma-nginx"
require "capistrano/bundler"
```
when i try `cap -T` i have this error :

(Backtrace restricted to imported tasks)
cap aborted!
LoadError: cannot load such file -- capistrano/puma
/Applications/MAMP/htdocs/Lab/deploy/Capfile:31:in `<top (required)>'
(See full trace by running task with --trace)

Thanks for your help

**Comment by danieldraper** [comment]
Currently running into this problem on a new Rails 6 project. Did you ever resolve the issue @webinti?

**Comment by seuros** [comment]
What version of the gem ?  Did you read the readme, you need to require the process manager

**Comment by meliborn** [comment]
```ruby
require 'capistrano/puma'
install_plugin Capistrano::Puma
install_plugin Capistrano::Puma::Systemd
```

![Снимок экрана 2021-06-01 в 20 54 33](https://user-images.githubusercontent.com/735194/120369166-923df780-c31b-11eb-9d12-a1828ccf2731.png)

```
ruby '3.0.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.3.2'
```

**Comment by seuros** [comment]
bundle exec cap -T
