### ISSUE TITLE
Document in README that puma.rb is only updated once

### ISSUE THREAD

**Issue by betelgeuse** [seuros/capistrano-puma#294]
A random reader of the current README would have the reasonable expectation that, for example, puma_env changes would take effect on every deploy. However, this is not the case as puma.rb is only uploaded once. 

https://github.com/seuros/capistrano-puma/blob/87bfd747bd43a19b5d214e0272b76fb723cf1f5f/lib/capistrano/tasks/puma.rake#L82

**Comment by seuros** [comment]
I think we should remove that generation and just let people use config/puma/${env}.rb
