### ISSUE TITLE
Make the 'append' argument in template configurable.

### ISSUE THREAD

**Issue by lanzhiheng** [seuros/capistrano-puma#296]
I think we should make the last argument in `stdout_redirect` configurable.

```
    def stdout_redirect(stdout=nil, stderr=nil, append=false)
      @options[:redirect_stdout] = stdout
      @options[:redirect_stderr] = stderr
      @options[:redirect_append] = append
    end
```

Fetch the value in our [template](https://github.com/seuros/capistrano-puma/blob/81647bc8402ff1cb485e81d9ec803dfec31aa851/lib/capistrano/templates/puma.rb.erb#L11)

**Comment by seuros** [comment]
why will you reset the log file at every deploy ?

**Comment by lanzhiheng** [comment]
@seuros After too much deploy, the log about puma grew bigger. Sometimes I want to restrict the logs's size in my project. Like [this](https://github.com/lanzhiheng/stone/issues/77). But I think that puma can't do the same as Rails's log by configuring the size of the it

```
  logger = ActiveSupport::Logger.new(Rails.root.join('log/production.log'), 0, 10.megabytes)
  logger.formatter = config.log_formatter
  config.logger    = ActiveSupport::TaggedLogging.new(logger)
```

So, to handle this problem, I think it will be better to reset the log file at every deploy.

**Comment by lanzhiheng** [comment]
If you consider it is acceptable, I can push a commit for this tweak.

**Comment by seuros** [comment]
that not a deployment responsability . You should not fix this issue by redploying.

Checkout logrotate , https://en.wikipedia.org/wiki/Log_rotation

**Comment by lanzhiheng** [comment]
Thanks for your advice. I will check it later.
