### ISSUE TITLE
Support for Puma 5.0

### ISSUE THREAD

**Issue by lizdeika** [seuros/capistrano-puma#297]
Hi,

Would be nice to have puma 5.0 support :)

At least one breaking change is due:
- `set :puma_daemonize` option should be removed  as daemonization is gone in 5.0.

**Comment by seuros** [comment]
Time to bump version .

**Comment by krim** [comment]
PR: https://github.com/seuros/capistrano-puma/pull/298

**Comment by dorianmariefr** [comment]
for you information, i am getting capistrano3-puma version 1.2.1 when using puma 5, had to force using 4.0.0 and downgrade puma

**Comment by seuros** [comment]
@dorianmariefr  for puma 5, you need to install version 5.0.0.beta1 and add the SystemD module.
