### ISSUE TITLE
Systemd integration

### ISSUE THREAD

**Issue by farnsworth** [seuros/capistrano-puma#302]
Hello,
maybe I'm wrong, but I have noticed that the systemd integration requires sudo and uses the system service manager.
Is there a reason for that?
Is there a way, playing with the config params, to skip the use of sudo and use the user system manager and lingering?
In alternative, maybe, the introduction of a new config parameter (for instance "puma_service_unit_user", as done in capistrano-sidekiq), could be usefull.

Thank you.

**Comment by seuros** [comment]
That is doable. I think i will release it in 5.1.0 
I just need to spin another server to test this new approach config.

**Comment by farnsworth** [comment]
Since I will implement it for my needs, if you agree, I can commit the changes in my fork and then create a pull request.

**Comment by seuros** [comment]
@farnsworth Of course, that the aim of Opensource :)

**Comment by shabeebk** [comment]
@seuros @farnsworth Do you think this is done already and is good to be used? I could see a [PR](https://github.com/seuros/capistrano-puma/pull/307), but doesn't look like it's merged.

**Comment by Eric-Guo** [comment]
Guess the status of the issue is #307 and later #319 merged and waiting for @shabeebk feedback?
