### ISSUE TITLE
5.0 version restart should be reload?

### ISSUE THREAD

**Issue by Eric-Guo** [seuros/capistrano-puma#303]
I notice 5.0 systems mode is simply restart the puma

```ruby
  desc 'Restart Puma service via systemd'
  task :restart do
    on roles(fetch(:puma_role)) do
      sudo "#{fetch(:puma_systemctl_bin)} restart #{fetch(:puma_service_unit_name)}"
    end
  end
```

But I guess it's not zero down time restart and should replace restart with reload?

As unit file define reload instead of restart.

```txt
[Unit]
Description=Puma HTTP Server for cybros (production)
After=network.target

[Service]
Type=simple
User=deployer
WorkingDirectory=/var/www/cybros/current
ExecStart=/home/deployer/.rbenv/bin/rbenv exec bundle exec puma -C /var/www/cybros/shared/puma.rb
ExecReload=/bin/kill -TSTP $MAINPID
ExecStop=/bin/kill -TERM $MAINPID
StandardOutput=append:/var/www/cybros/shared/log/puma_access.log
StandardError=append:/var/www/cybros/shared/log/puma_error.log

Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by Eric-Guo** [comment]
Should relative with #300

**Comment by storm2513** [comment]
Unless changes are made you can add this code to `deploy.rb`:
```
Rake::Task['puma:restart'].clear_actions

namespace :puma do
  desc 'Restart Puma service via systemd'
  task :restart do
    on roles(fetch(:puma_role)) do
      sudo "#{fetch(:puma_systemctl_bin)} reload #{fetch(:puma_service_unit_name)}"
    end
  end
end
```

**Comment by braindeaf** [comment]
I've tried this but the reload does nothing at all. All of the processes remain as they were.

**Comment by storm2513** [comment]
@braindeaf you need to add `ExecReload=/bin/kill -USR1 $MAINPID` to your `puma.service` file

**Comment by braindeaf** [comment]
Ah I see the default is...

ExecReload=/bin/kill -TSTP $MAINPID

I've been watching the processes and we were getting a 3 second delay as all the processes dropped and waiting for them to come back. I was expecting to see the parent process continue to exist (this is probably wrong) and the child processes to disappear. But all processes including the parent went. This is the case with the previous kill option and this one..

But....more importantly after this change it didn't stop serving it just paused briefly and then continued. Which I think is what we need.

In short, thanks very much :)
