### ISSUE TITLE
Don't know how to build task 'puma:restart'

### ISSUE THREAD

**Issue by tchret** [seuros/capistrano-puma#306]
Getting this error since I upgraded to **ruby 2.7.0**

```
Don't know how to build task 'puma:restart' (See the list of available tasks with `cap --tasks`)
Did you mean?  puma:workers:count
```

**Comment by seuros** [comment]
that not a ruby issue.
I think you forgot to select your service manager. Check the readme .

**Comment by tchret** [comment]
@seuros: appreciate the blazing-fast answer!

I've used the gem for a while - never had any problem til I upgrade ruby/rails.
Will try and let you know

**Comment by tchret** [comment]
adding solved my problem! 

```
install_plugin Capistrano::Puma::Daemon
```
