### ISSUE TITLE
Systemd Integration Bug

### ISSUE THREAD

**Issue by sharat94** [seuros/capistrano-puma#316]
This is with regards to the release under https://github.com/seuros/capistrano-puma/pull/307/files
Noticed that puma_systemctl_user config is used to set the system path however the same was not initialized in defaults.
Since we root systemd as opposed systemd user manager this resulted in our deployments to fail. 
We have set the user in our config for now but looks like a potential bug.

**Comment by seuros** [comment]
Ok, i will release a new version with the previous defaults.

**Comment by davegudge** [comment]
Fixed by https://github.com/seuros/capistrano-puma/pull/319
