### ISSUE TITLE
Pids for puma workers ?

### ISSUE THREAD

**Issue by danielristic** [seuros/capistrano-puma#323]
Hello,

I'm not sure if it's the expected behavior but when setting `puma_daemonize` to `true`, I would expect the `tmp/pids/` folder to also contain the individual workers pids along with the one for the main process.

This would make monitoring the individual workers in monit easier.

**Comment by seuros** [comment]
puma_daemonize is not supported anymore. Puma don't handle the daemonization after v5.

**Comment by danielristic** [comment]
I'm using v4.0.0 of this gem and puma 4 which still supports daemonization and was just wondering if it was expected behavior that workers don't have their own pid files.
