### ISSUE TITLE
deploy user needs sudo access to use systemd

### ISSUE THREAD

**Issue by ivan-denysov** [seuros/capistrano-puma#326]
Hi. 

Is it possible to use systemd to manage puma without giving sudo access to the user? Are there any technical limitations that prevent us from doing that?

**Comment by seuros** [comment]
You can give access to user for sudo to only a very specific command/argument. with /etc/sudoers

ivan  ALL=(root)  /bin/systemctl

If you run the app in with your user/group , systemd should be able to stop/run it without sudo.
