### ISSUE TITLE
Systemd config requires sudo

### ISSUE THREAD

**Issue by heaven** [seuros/capistrano-puma#327]
This should work the same way as with `capistrano-sidekiq` and install the config to `$HOME/.config/systemd`.

I don't see much sense in creating a separate `deploy` user and adding it to the sudoers.

**Comment by heaven** [comment]
My bad, I've just found `puma_systemctl_user`.

**Comment by Randall-Coding** [comment]
To elaborate for anyone confused by this, I solved this by adding this line to deploy.rb

`set :puma_systemctl_user, fetch(:user)`
