### ISSUE TITLE
Job type reload is not applicable for unit

### ISSUE THREAD

**Issue by kirqe** [seuros/capistrano-puma#332]
Hey there. Capistrano-puma used to do `/bin/systemctl RESTART puma_app_production` at the end of `cap production deploy` I did bundle updated aaand...

now it does reload instead of restart which leads to
` Failed to reload puma_app_production.service: Job type reload is not applicable for unit puma_app_production.service.`

**Comment by seuros** [comment]
Did you regenerate the systemd  file ? 

Reloading allows zero downtime deployment

**Comment by kirqe** [comment]
@seuros I did `systemctl daemon-reload`
