### ISSUE TITLE
Does the latest version work with rhel/centos?

### ISSUE THREAD

**Issue by keithslater** [seuros/capistrano-puma#341]
Trying to get the latest version running however our servers are running an old Amazon AMI which I believe is rhel under the hood. This doesn't seems to have systemd and when we deploy we get errors about systemd not existing. Are there any solutions to upgrade to the latest version? It seems jungle has a case for rhel, but I'm not sure if we need that.

**Comment by seuros** [comment]
The old AMI are using upstart. the new one are using systemd.
