### ISSUE TITLE
Service "Type" should be configurable, or the sd_notify gem should be a dependency of this gem

### ISSUE THREAD

**Issue by zedtux** [seuros/capistrano-puma#343]
I'm about to submit a PR to this gem in order to allow passing args to puma from the service file, but while I was inspecting that file, I saw you've [hardcoded the `notify` value to the Service `Type`](https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/templates/puma.service.erb#L18-L19).

Before to come to this gem, I made my own service file by hand on my server, and I have started with the same `Type=notify` which prevented the service from starting after the timeout defined from the `WatchdogSec`.
An error message suggested to have the [sd_notify](https://github.com/agis/ruby-sdnotify) gem in order to get a Ruby app to be compatible with the `Type=notify`. Therefore I have changed the service `Type` to `simple` and removed the `WatchdogSec` and my service now works.

With that in mind, I'm opening this issue to solve this by :
* Either making the service `Type` an option that could be `:notify` or `:simple`
* Either add the sd_notify gem as a dependency of this gem

**Comment by seuros** [comment]
i pushed this fix in master.
I did a full refactoring/rewrite of the gems. 

You can find usage in this sample app https://github.com/seuros/capistrano-example-app

Let me know if you find any bug.

**Comment by zedtux** [comment]
Thank you @seuros !
