### ISSUE TITLE
Why does Capistrano not launch my Rails app itself? Why do I need capistrano-puma gem?

### ISSUE THREAD

**Issue by jmuheim** [seuros/capistrano-puma#346]
I'm just wondering whether I didn't get something. I read through some Capistrano tutorials, and they don't seem to mention anything about starting/restarting the Rails app on the server. It just seems to happen right out of the box.

Well, in my case it doesn't. I have to manually `cd` into the `releases/current` folder and run something like `bin/rails -e production` after each release. Why's that? Do I misunderstand something? Is Capistrano only responsible for copying files to my host, but not for running my Rails app on it? Is this the reason why `capistrano-puma` gem exists? 🤔

**Comment by seuros** [comment]
Yes capistrano is just a deployment framework. What app you running is your choice. 

Some people use it to deploy laravel and node apps
