### ISSUE TITLE
`cap production puma:config` results in `Don't know how to build task 'puma:config'`

### ISSUE THREAD

**Issue by jmuheim** [seuros/capistrano-puma#347]
In the README:

![CleanShot 2022-10-06 at 08 51 42@2x](https://user-images.githubusercontent.com/1814983/194233896-53f2d945-6297-49d9-8f95-e659dc1af926.png)

Result:

![CleanShot 2022-10-06 at 08 52 33@2x](https://user-images.githubusercontent.com/1814983/194234062-34cca8fc-859f-4f56-9929-950cf07f78b3.png)

**Comment by seuros** [comment]
I will update readme now.
