### ISSUE TITLE
Puma 6.x

### ISSUE THREAD

**Issue by jules-w2** [seuros/capistrano-puma#349]
Hello @seuros 

capistrano3-puma does not seem ready for version 6.x of Puma, we are going back to version 1.2.1.

Do you have on ETA date for a new release ?

Bests,

bundle update
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
......
**Installing puma 6.0.0 (was 5.6.5) with native extensions**
**Fetching capistrano3-puma 1.2.1 (was 5.2.0)**
**Installing capistrano3-puma 1.2.1 (was 5.2.0)**
Bundle updated!

**Comment by seuros** [comment]
Hold on 10 minutes. I releasing a alpha version for you.

**Comment by seuros** [comment]
@jules-w2 Please clean up your systemd service and use the latest version 

gem 'capistrano3-puma' ,  '=>6.0.0.beta.1'

```
bin/cap staging puma:install 
```

In the new version you need to have the puma config  checked out in config/puma.rb or config/puma/production.rb

There is a sample app in the readme.

The same apply to capistrano-sidekiq if you use it.

I would appreciate if you help me getting this version out.

**Comment by jules-w2** [comment]
@seuros ,

I spent my whole day on it, but it's working, my app production app is  running with Puma 6! 


In the end to have a configuration that works with the same settings as before, I had to:

1. Install Puma & capistrano-puma

```ruby
gem 'puma' , '>= 6'
gem 'capistrano3-puma' , '>= 6.0.0.beta.1'
```


2.  set 3 values into the config/deploy.rb file to keep the same behavior as version 5.x

```ruby
set :puma_systemctl_user, :system
set:puma_access_log,        "#{fetch(:deploy_to)}/shared/log/puma_access.log"
set:puma_error_log,             "#{fetch(:deploy_to)}/shared/log/puma_error.log"

```

3. Update the service on the server 

```ruby
cap production puma:install
```


3. add  config for puma file   (config/puma/production.rb)

```ruby
my_app_path = "path/to/deploy"


directory   "#{my_app_path}/current"
rackup      "#{my_app_path}/current/config.ru"
environment "staging"

tag ""

pidfile         "#{my_app_path}/shared/tmp/pids/puma.pid"
state_path      "#{my_app_path}/shared/tmp/pids/puma.state"
stdout_redirect "#{my_app_path}/shared/log/puma_access.log", "#{my_app_path}/shared/log/puma_error.log", true


threads 0,16


bind "unix://#{my_app_path}/shared/tmp/sockets/puma.sock"

workers 0


restart_command "bundle exec puma"


prune_bundler


on_restart do
  puts "Refreshing Gemfile"
  ENV["BUNDLE_GEMFILE"] = ""
end

```

5. deploy the app 

```ruby
cap production deploy

Tanks :)

**Comment by seuros** [comment]
Perfect. Thank you.  

I will prepare a final release soon.

btw except the 

```
threads 0,16

bind "unix://#{my_app_path}/shared/tmp/sockets/puma.sock"

workers 0
```

You don't need the other settings in puma.rb 

I recommend you to use ENV variables to configure it like in this example : https://github.com/seuros/capistrano-example-app/blob/main/config/puma/production.rb#L4-L6
