### ISSUE TITLE
Couple of issues with 6.0.beta

### ISSUE THREAD

**Issue by mtomov** [seuros/capistrano-puma#351]
Hi,

Thanks so much for maintaining and improving this library!

I was able to test the latest version of the library that's on master, and came across 2 issues:

1. `puma_bind` is still [used here](https://github.com/seuros/capistrano-puma/blob/6d4e5e7d37f760448db099b45c26d63138865a4f/lib/capistrano/puma.rb#L26) although the default of it was deleted [here](https://github.com/seuros/capistrano-puma/pull/342/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L178) 

2. To use a socket as a medium between Nginx and Puma, I had to add ` -b unix:///home/deploy/myapp/shared/tmp/sockets/puma.sock` to the `ExecStart` command in the service. Example:
    ```
    ExecStart=/usr/lib/rbenv/bin/rbenv exec bundle exec puma -e production -b unix:///home/deploy/myapp/shared/tmp/sockets/puma.so
    ```

    with this in the nginx config

    ```
    upstream puma_zoomtoslackstatusupdater_production {
      server unix:/home/deploy/myapp/shared/tmp/sockets/puma.sock fail_timeout=0;
    }
    ```
  
  Previously, the socket bind would automatically be added.

Edit: I think the reason for 2. is that previously the production puma config file was specified in the service as the one in `shared/puma.rb`, which was transparently uploaded. This previous `shared/puma.rb` config file used to have a `unix` socket bind inside. 

To resolve the issue, I copied the server generated `shared/puma.rb` and placed it in `config/puma/production.rb` and committed as part of the repository.

So I think it really is just 1) that's still an issue for new installations/migrations.

Thanks!

**Comment by ccastillop** [comment]
Yea, it was a little confusing for me

In order to still use nginx config generator, I have to add `set :puma_bind, "unix://#{shared_path}/tmp/sockets/puma.sock"    #accept array for multi-bind` to the `config/deploy/production|staging.rb`
