### ISSUE TITLE
WatchdogSec causes error when using Type=simple

### ISSUE THREAD

**Issue by harshalbhakta** [seuros/capistrano-puma#354]
I haven't included `sd_notify` gem in my Gemfile. 

````shell
# Gemfile
gem 'capistrano', '~> 3.17', '>= 3.17.1', require: false
gem 'capistrano-bundler', '~> 2.1', require: false
gem 'capistrano-rails', '~> 1.6', '>= 1.6.2', require: false
gem 'capistrano-rbenv', '~> 2.2', require: false
gem 'capistrano3-nginx', '~> 3.0', '>= 3.0.4', require: false
gem 'capistrano3-puma', '~> 6.0.0.beta.1', require: false
````

`bundle exec cap production puma:install` produces below block in the service file.

````shell
[Service]
Type=simple
WatchdogSec=10
````

When I deploy my code using `bundle exec cap production deploy`, it shows below error in `journalctl`.

````shell
Dec 05 22:22:07 blog-rails-deployment-1 systemd[20255]: blog_puma_production.service: Watchdog timeout (limit 10s)!
Dec 05 22:22:07 blog-rails-deployment-1 systemd[20255]: blog_puma_production.service: Killing process 22263 (bundle) with signal SIGABRT.
Dec 05 22:22:07 blog-rails-deployment-1 systemd[20255]: blog_puma_production.service: Killing process 22280 (bundle) with signal SIGABRT.
Dec 05 22:22:07 blog-rails-deployment-1 systemd[20255]: blog_puma_production.service: Killing process 22283 (bundle) with signal SIGABRT.
Dec 05 22:22:07 blog-rails-deployment-1 systemd[20255]: blog_puma_production.service: Main process exited, code=dumped, status=6/ABRT
Dec 05 22:22:07 blog-rails-deployment-1 systemd[20255]: blog_puma_production.service: Failed with result 'watchdog'.
````

Does `WatchdogSec` not work with `Type=simple`? If it doesn't, I think we should add a condition to only add `WatchdogSec` when `service_unit_type` is `notify`. The [systemd man page](https://www.freedesktop.org/software/systemd/man/systemd.service.html#WatchdogSec=) does not specifically say if it will work with `Type=simple` or not, but it does mention that "The service must call [sd_notify(3)](https://www.freedesktop.org/software/systemd/man/sd_notify.html#) regularly with "WATCHDOG=1" (i.e. the "keep-alive ping").". When using `Type=simple`, `sd_notify` gem might not be added, is that what is causing the above error?

````shell
[Service]
Type=<%= service_unit_type %>

<% if service_unit_type == "notify" %>
WatchdogSec=10
<% end %>
````

**Comment by HLFH** [comment]
Reopen?
