### ISSUE TITLE
Deploying a new app to a staging server won't start/restart puma/systemd

### ISSUE THREAD

**Issue by salex** [seuros/capistrano-puma#355]
See issue on GitHub Capistrano 

[Deploying a new app to a staging server won't start/restart puma/systemd](https://github.com/capistrano/capistrano/issues/2123)

It may be your issue

**Comment by jesperronn** [comment]
@salex original linked issue is closed https://github.com/capistrano/capistrano/issues/2123

 could you as a minimum at least amend your issue description to have the text of the original issue?

**Comment by jesperronn** [comment]
I had the same problem after recent deployment (using v5.2.0 of this plugin). As a temporary workaround I could `chown ` the puma logfiles to my puma user, so that the files were not owned by `root`
