### ISSUE TITLE
release 5.x with support for Puma v6.0

### ISSUE THREAD

**Issue by jesperronn** [seuros/capistrano-puma#358]
currently released version 5.2.0 does is constrained to puma (>= 4.0, < 6.0), which prevents Capistrano3-Puma from being upgraded.

here is the error message i see:

```
Bundler could not find compatible versions for gem "puma":
  In Gemfile:
    puma (~> 6.0)

    capistrano3-puma (~> 5.2) was resolved to 5.2.0, which depends on
      puma (>= 4.0, < 6.0)
```

The upcoming release v6 of capistrano3-puma has several breaking changes and might not be fit for existing installations. 

Since it seems there are no changes in Puma v6.0 that would break v5.2.0 of the plugin, then I suggest making a new version with puma v6 support. Perhaps just call it v5.3.0?

**Comment by thr3a** [comment]
I would like to use puma 6.x as well, but I can't use it because there are many breaking changes in the latest version of capistrano-puma.
I would be happy if puma 6.x could be used with capistrano-puma 5.x.
