### ISSUE TITLE
v6.0.0.beta.1 breaks Nginx functionality

### ISSUE THREAD

**Issue by jesperronn** [seuros/capistrano-puma#360]
This example from [docs/nginx.md](https://github.com/seuros/capistrano-puma/blob/master/docs/nginx.md) is broken in new v6.0.0.beta.1 release:

    # Capfile
    install_plugin Capistrano::Puma::Nginx

Now `cap -T` is broken:

```
$ cap -T
(Backtrace restricted to imported tasks)
cap aborted!
NameError: uninitialized constant Capistrano::Puma::Nginx

install_plugin Capistrano::Puma::Nginx # if you want to upload a nginx site template
                               ^^^^^^^
~/myproject/Capfile:33:in `<top (required)>'
(See full trace by running task with --trace)
```

Excerpt of my Capfile:

```ruby
# for capistrano puma:
require 'capistrano/puma'
install_plugin Capistrano::Puma # Default puma tasks
# install_plugin Capistrano::Puma::Monit  # if you need the monit tasks
install_plugin Capistrano::Puma::Nginx # if you want to upload a nginx site template
install_plugin Capistrano::Puma::Systemd # if you use SystemD
```

Even though nginx is deprecated, I think that restart of nginx is still a useful functionality also for a v6 going onwards

**Comment by climatebrad** [comment]
This is an open bug.

**Comment by climatebrad** [comment]
The solution to this is to include 
`require 'capistrano/puma/nginx'`

before calling 
`install_plugin Capistrano::Puma::Nginx`

**Comment by climatebrad** [comment]
That said, the Nginx functionality has been deprecated.
