### ISSUE TITLE
prune_bundler option

### ISSUE THREAD

**Issue by masterkain** [seuros/capistrano-puma#43]
can this option `prune_bundler`:

https://github.com/puma/puma/search?q=prune_bundler&ref=cmdform

replace the `ENV["BUNDLE_GEMFILE"]` workaround in the template?

https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/templates/puma.rb.erb#L23

I just stumbled upon this config option and I'm not even entirely sure about the implications yet, thought I might give you a heads up.

**Comment by crhan** [comment]
still don't work very well in my situation and it did compatible with `preload_app!`

see the line notes here https://github.com/seuros/capistrano-puma/commit/cddd27438e2c272c80598368cee889d8f620744b
