### ISSUE TITLE
Problem with uploading puma.rb using puma:config command

### ISSUE THREAD

**Issue by x44x45x41x4E** [seuros/capistrano-puma#63]
I created my own puma.rb before to be used with foreman but then I stumbled to this gem and realized that it will be easier and organized for me to use this. I've been trying to find a solution for this problem but no one seems to  have encountered it yet besides me. When I run `cap production puma:config` I always end up with this error: 

> Uploading ~/app/shared/config/puma.rb 0.0%
> cap aborted!
> SSHKit::Runner::ExecuteError: Exception while executing on host ec2-vps.com: >scp:~/app/shared/config/puma.rb: No such file or directory

Please note on the last line that s is displayed in a unicode character. Like this: [scp](http://i.imgur.com/jVvB8NP.png), but I don't think it's the problem.
The same issue occurs when I try to deploy my app using `cap production deploy`. And just to clear things up, I assume that the puma:config command uploads puma.rb base on the settings I specified in deploy.rb or do I have to make my own puma.rb on my VPS?

Thanks. Your answer will be appreciated.

**Comment by almirsarajcic** [comment]
Had the same issue. Use absolute path for profit.
