### ISSUE TITLE
puma monit config can not start with production and rbenv tips

### ISSUE THREAD

**Issue by kyoyk** [seuros/capistrano-puma#78]
Update:

Fix not start with production.

add RACK_ENV to /etc/environment

```
RAILS_ENV=production
RACK_ENV=production
```

*rbenv tips*

```
set :rbenv_type, :system
set :rbenv_ruby, '2.1.2'
set :rbenv_path, '/var/opt/rbenv'
set :rbenv_prefix, "RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)} #{fetch(:rbenv_path)}/bin/rbenv exec"
```

But still not work fine. It running, but production env has some problem, make errors in production.log.

I will go on find, how to fix.

**Comment by seuros** [comment]
set :rack_env and :rails_env
