### ISSUE TITLE
No feedback on missing shared/log directory

### ISSUE THREAD

**Issue by sime** [seuros/capistrano-puma#79]
Hello,

I'm using capistrano-puma for the first time and ran into some difficultlies on first run.

Firstly puma:start failed silently due to missing a missing log directory.

Prior to that, puma:start failed loudly when share/tmp/pids and shared/tmp/sockets could not be found.

Is it fair to fair that puma:check should notify the user about missing directories?

**Comment by aidistan** [comment]
I have met the same situation as yours. But there says,

> Ensure that the following directories are shared (via linked_dirs):
> ```
> tmp/pids tmp/sockets log
> ```

which fixed my issue : )
