### ISSUE TITLE
Status file not found

### ISSUE THREAD

**Issue by suratpyari** [seuros/capistrano-puma#83]
I have deployed my application and it worked once, but again when I tried to deploy it again I received following error:

DEBUG[a90fa6f0] Command: cd /var/www/apps/blazarsol/releases/20141126143552 && /usr/bin/env bundle exec pumactl -S /var/www/apps/blazarsol/shared/tmp/pids/puma.state restart
DEBUG[a90fa6f0]     Status file not found: /var/www/apps/blazarsol/shared/tmp/pids/puma.state
DEBUG[a90fa6f0]  
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 54.169.166.162: Exception while executing on host 54.169.166.162: bundle exit status: 1
bundle stdout: Nothing written
bundle stderr: Nothing written

**Comment by micahalcorn** [comment]
@seuros I am having a similar issue. I cannot run `cap production puma:config` (Don't know how to build task).

[Here is my Gemfile.lock](http://pastie.org/private/cgsm9cz3bnsqtn5ruacqsq) after running `bundle update` and `bundle install`.

When I run `cap production deploy:initial --trace`, I get "Status file not found: /home/myuser/apps/myapp/shared/tmp/pids/puma.state".

**Comment by seuros** [comment]
@micahalcorn, did you require the gem in your Capfile

**Comment by micahalcorn** [comment]
**Capfile**:
```ruby
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rails'
require 'capistrano/bundler'
require 'capistrano/rvm'
require 'capistrano/puma'
require 'capistrano/puma/nginx'

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

`cap -T` output:
```
...
cap install                        # Install Capistrano, cap install STAGES=staging,p...
cap puma:make_dirs                 # Create Directories for Puma Pids and Socket
cap puma:nginx_config              # Setup nginx configuration
cap puma:overview                  # Show status of puma for all applications
cap puma:restart                   # Restart puma instance for this application
cap puma:start                     # Start puma instance for this application
cap puma:status                    # Show status of puma for this application
cap puma:stop                      # Stop puma instance for this application
cap rvm:check                      # Prints the RVM and Ruby version on the target host
```

**Comment by seuros** [comment]
You have the wrong gem. 

`gem 'capistrano3-puma'`

**Comment by micahalcorn** [comment]
My Gemfile.lock is showing the following:

```Ruby
GIT
  remote: git://github.com/seuros/capistrano-puma.git
  revision: 5fd95d92e52bf1a2169cc126c6196f3f8991e265
  specs:
    capistrano3-puma (0.8.5)
```

**Comment by seuros** [comment]
@micahalcorn : There is something wrong then, i dont have `cap puma:make_dirs                 # Create Directories for Puma Pids and Socket` in this gem. 
I can take a quick look at your app if the repo is public or if you can add me temporary (contact me by email).

**Comment by bmedici** [comment]
Same problem gere, I made a ```bundle update```and have this in my Gemfile.lock:
```
capistrano3-puma (0.9.0)
  capistrano (~> 3.0)
  puma (>= 2.6)
```
With a ```cap staging puma:nginx_config```I get:
```
cap aborted!
Don't know how to build task 'puma:nginx_config'
```
Any idea ?

**Comment by seuros** [comment]
you have to require the nginx task manually.

**Comment by bmedici** [comment]
@seuros thanks for your suggestion, right, I added 
```
require 'capistrano/puma/nginx'
```
but still have an error with ```template_puma```
```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host XXXXXXXX: undefined method `template_puma' for #<SSHKit::Backend::Netssh:0x007fe677223340>

NoMethodError: undefined method `template_puma' for #<SSHKit::Backend::Netssh:0x007fe677223340>

Tasks: TOP => puma:nginx_config
```

**Comment by bmedici** [comment]
Oh, found the problem. Has to completely uninstall other versions:
```
gem uninstall capistrano-puma
````

**Comment by fruwe** [comment]
@bmedici deleting the old gem helped! thanks
