### ISSUE TITLE
Add Inspeqtor support

### ISSUE THREAD

**Issue by mperham** [seuros/capistrano-puma#92]
It would be great to see capistrano-puma trigger Inspeqtor's deploy window during deploys, a la capistrano-sidekiq.

**Comment by seuros** [comment]
Adding https://github.com/seuros/capistrano-inspeqtor will open the 5 min deploy window.

**Comment by mperham** [comment]
Cool!

**Comment by mperham** [comment]
Updated wiki: https://github.com/mperham/inspeqtor/wiki/Deployments#capistrano
